# Generated by Django 2.2.19 on 2021-04-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_collection_movie'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
