# Generated by Django 2.2.19 on 2021-04-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_requestcounter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestcounter',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
